name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm check
      - run: sudo pnpm test
        working-directory: tests
